name: "Update Angular Action"
on:
  schedule:
    - cron: '30 12 * * 3' # Jeweils Mittwoch um 12:30

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    steps:
      - name: Updating ng dependencies # the magic happens here!
        uses: fast-facts/ng-update@v1
        with:
          base-branch: main
          rep-token: ${{ secrets.GITHUB_TOKEN }}
