name: "Update Angular Action"
on:
  workflow_dispatch:
  schedule:
    - cron: '00 13 * * 4' # Jeweils Donnerstag um 13:00

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    steps:
      - name: Updating ng dependencies # the magic happens here!
        uses: fast-facts/ng-update@v1
        with:
          base-branch: main
          rep-token: ${{ secrets.GITHUB_TOKEN }}
